---
- name: This sets up an apache webserver
  hosts: all
  become: true

  tasks:
  - name: Install the apache package
    apt:
      name: apache2
      state: present

  - name: start the apache service
    service:
      name: apache2
      state: started
      enabled: yes